name: deploy to lambda

on: [push]
 

jobs:
  wait:
    runs-on: ubuntu-latest
    steps:
      - name: Wait
        run: sleep 30
  download_artifact:
    runs-on: ubuntu-latest
    needs: wait
    steps:
       #  to check out 
      - name: Checkout
        uses: actions/checkout@v3
       #  downloads artifact from other workflow artifact
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build.yml
          workflow_conclusion: success
      - name: Test
        run: ls
  deploy_to_lamda:
   #  deploys the file to AWS lamda from the downloaded artifact
    name: deploy lambda from source
    runs-on: ubuntu-latest
    steps:
      - name: checkout source code
        uses: actions/checkout@v1
      - name: deploy code to lamda
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: demo-lamda-gitactions
          source: src/main.py
 
